### ISSUE TITLE
Add option to exit with error on any warnings/errors

### ISSUE THREAD

**Issue by maxlapides** [bitrise-steplib/bitrise-step-flutter-analyze#10]
It looks like a recent change now prevents the step from exiting with an error when only info warnings are raised. However, we preferred the old behavior where the step would fail on ANY warning or error. I think it would be best to add an option to exit with error in this case if we prefer.

For reference, here is the change that created the behavior that we do NOT want: https://github.com/bitrise-steplib/bitrise-step-flutter-analyze/pull/3

**Comment by doc-rj-celltrak** [comment]
I agree, an option would be great. The default behavior is supposed to be that warnings don't fail the analysis step, but the underlying tools seem to allow for customizing this for warnings (but not for info)... see the Dart analysis rules here -- https://dart.dev/guides/language/analysis-options#customizing-analysis-rules

**Comment by non-binary** [comment]
Hi @maxlapides @doc-rj-celltrak,

Thank you for reaching out and sharing your concerns.

I have escalated this to our tooling team to discuss potential solutions.

Cheers,
Luna

**Comment by non-binary** [comment]
@maxlapides @doc-rj-celltrak Can you please share a link to a build that reproduces this behaviour?

**Comment by maxlapides** [comment]
@non-binary This build should have failed on the `flutter-analyze` step, but it succeeded because the issues raised were only `info` severity. I still want the build to fail when there are _any_ issues raised, regardless of severity. https://app.bitrise.io/build/87e8d7922a9ead60

**Comment by non-binary** [comment]
If you select a previous version of the step, then you will have the previous logic (step fails for warning as well). In this case the tooling team has decided it's not an urgent issue as there is a workaround for the users that want the previous logic in the meantime. I've created an internal JIRA ticket and they will schedule a fix as they see fit. Thanks for your patience.

**Comment by ncuillery** [comment]
Any update on this?

I'm using a custom script step as a workaround.

**Comment by non-binary** [comment]
Hi @ncuillery,

It is still in backlog.

**Comment by non-binary** [comment]
Hi @ncuillery,

It is still in backlog. Do you mind sharing the workaround for others in case they find this in the meantime?

**Comment by ncuillery** [comment]
Sure:

1. Insert a "Script" step
2. Declare the following in "Script content":

```
#!/usr/bin/env bash

# fail if any commands fails
set -e
# debug log
set -x

echo "Remember to use the official Flutter test step when https://github.com/bitrise-steplib/bitrise-step-flutter-analyze/issues/10 will be fixed".

flutter analyze
```

**Comment by non-binary** [comment]
Thank you @ncuillery

**Comment by Szabadember** [comment]
Hi @maxlapides ,
there is a new step input in [0.2.0](https://github.com/bitrise-steplib/bitrise-step-flutter-analyze/releases/0.2.0) which enables you to specify the fail severity. This makes it possible to make the step fail on warning/info level analysis issues. This will be available from the workflow editor soon.

**Comment by maxlapides** [comment]
@Szabadember great, thanks so much!
