### ISSUE TITLE
Poor execution time

### ISSUE THREAD

**Issue by ncuillery** [bitrise-steplib/bitrise-step-flutter-analyze#11]
The command `flutter analyze` takes about 3 seconds to run locally, but on Bitrise, it consistently takes between 14 and 15 seconds.

Any reason why the analysis is 5 times slower?
AFAIK, there is no caching used by dart analyzer.

My app is a fresh Flutter counter app generated with `flutter create`.
My laptop is a not so fancy MacBook Pro 2017, SSD and 8Gb.

Note: a manual script step that run `flutter analyze` does the same thing as this step (~15s execution time).

**Comment by Roland-Bak** [comment]
Hi there @ncuillery!

Our standard MacOS machines have the following specifications:

- 2 vCPU
- Intel® Xeon® CPU E5-2697 v2 @ 2.70GHz
- 4 GB RAM

So the difference in speed is either that Virtual Machines are built and destroyed in the course of the build, it does not accumulate dependenices over the years like a local machine does.

If you would like your step to run faster, you might try switching to Elite Machines, you can see the specifications here: 

- 4 vCPU
- Intel® Xeon® CPU E5-1650 v2 @ 3.5GHz
- 8 GB RAM

Hope this helps! 🙂
