### ISSUE TITLE
Step fails on "info" level warnings with severity level "error" if the file name contains sub-string "error"

### ISSUE THREAD

**Issue by andriimaryskevych** [bitrise-steplib/bitrise-step-flutter-analyze#14]
The output of the flutter analyzer :
```
info • Sort constructor declarations before other members • lib/model/response/favorites_error_response.dart:41:11 • sort_constructors_first
```

The file with the warning has sub-string "error" inside.
This string matches the error regex
```
/error.+\.dart:\d+:\d+/
```
but should be ignored as the level of the warning is 'info'.
This can be fixed by adding a caret symbol `^` at the beginning of the string and a space after the severity level:
```
/^error .+\.dart:\d+:\d+/
```

**Comment by mjones-droid** [comment]
Hi @andriimaryskevych! Our "Flutter Analyze" step does mostly the same thing as running "flutter analyze" on your local machine. 

Would you mind trying to see if this replicates locally? If it does, then this is a bug with Flutter not with Bitrise. Thanks!

**Comment by andriimaryskevych** [comment]
Hi @mjones-droid, the issue is with the regular expression inside this plugin in the `hasAnalyzeError` function.

`flutter analyze` just outputs the analyzer result to the stdout and the `bitrise-step-flutter-analyze` just picks it up and provides to the  `hasAnalyzeError` together with the severity level `(cmdOutput string, failSeverity string)`. The function determines whether the analyzer has detected issues based on the provided severity using the regular expression. And this regex may report false positive, based on the case that I described above.

Here is a small JS example:
```
var a = 'info • Sort constructor declarations before other members • lib/model/response/favorites_error_response.dart:41:11 • sort_constructors_first'

a.match(/error.+\.dart:\d+:\d+/)
```

Output:
```
[ 'error_response.dart:41:11',
  index: 89,
  input: 'info • Sort constructor declarations before other members • lib/model/response/favorites_error_response.dart:41:11 • sort_constructors_first',
  groups: undefined ]
```

So, the issue that `flutter analyzer` reports has a 'info' severity, but the `hasAnalyzeError` function will see an 'error' here

**Comment by mjones-droid** [comment]
That's logical. I'm filing a bug report with the dev's regarding this. Thanks!

**Comment by istvankovacs-bitrise** [comment]
Many thanks for reporting it! The issue was fixed by [this](https://github.com/bitrise-steplib/bitrise-step-flutter-analyze/pull/15) PR. It is going to go live with the next release!
