### ISSUE TITLE
Outdated analytics plugin, used format version is lower then host bitrise-cli's format version, please update the plugin

### ISSUE THREAD

**Issue by ra9r** [bitrise-steplib/bitrise-step-flutter-analyze#4]
When running a Flutter build project I am getting a failure on the Flutter Analyze step.  The only message I get is this:

> Outdated analytics plugin, used format version is lower then host bitrise-cli's format version, please update the plugin

and then I am directed here.  I am new to Bitrise, so I have no idea where to start to debug this step.  Here is what I've tried to solve the issue ...

1. Remove the Flutter Analyze step from the workflow.  No result .. in fact it seems to run this step regardless what I do (yes I did save the change).

2. I've tried to set the version field (via the step's UI in the Workflow Editor) to "latest".  Again, no change in result.

I don't know what else to try.  Any suggestions?

**Comment by bitce** [comment]
Hi @ra9r!

The message pasted is likely not the error, can you please include a build URL about these issues so we may take a look at them?

**Comment by ra9r** [comment]
I was able to get past that error … you are right .. it had nothing to do
with the analytics.  I’m new to reading the logs … sorry for the false
alarm.  Love the service so far!  Now if only Apple and Facebook weren’t
such a pain in my ass to configure life would be roses!

-- 
Rodney Aiglstorfer

On July 3, 2019 at 3:01:46 AM, Bence Kubik (notifications@github.com) wrote:

Hi @ra9r <https://github.com/ra9r>!

The message pasted is likely not the error, can you please include a build
URL about these issues so we may take a look at them?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitrise-steplib/bitrise-step-flutter-analyze/issues/4?email_source=notifications&email_token=AEAMDSGH5KWQZMXCXELC6BDP5R2ITA5CNFSM4H4LQM7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZD6OVY#issuecomment-508028759>,
or mute the thread
