### ISSUE TITLE
Step fails due to "info" level warnings

### ISSUE THREAD

**Issue by doc-rj-celltrak** [bitrise-steplib/bitrise-step-flutter-analyze#6]
In my first bitrise flutter build, flutter-analyze is marked as a failure because of "info" level warnings: https://app.bitrise.io/build/9729b27168aad1ba

Info level is not supposed to cause analysis to fail: https://dart.dev/guides/language/analysis-options#customizing-analysis-rules

This appears to be a problem with the flutter tool itself: https://github.com/flutter/flutter/issues/20855

However, there is a workaround here: https://gist.github.com/cubuspl42/ad277079f2cbc3c0bddb10f63ba1a3d2

**Comment by doc-rj-celltrak** [comment]
Looks like Bitrise already has a workaround here: https://github.com/bitrise-steplib/bitrise-step-flutter-analyze/pull/3

Is it not used in production yet?

**Comment by doc-rj-celltrak** [comment]
I just double-checked. This is still an issue in version 0.1.1.

**Comment by doc-rj-celltrak** [comment]
Opened PR: https://github.com/bitrise-steplib/bitrise-step-flutter-analyze/pull/7

**Comment by bitce** [comment]
Hi @doc-rj-celltrak! Sorry for the delay, we notified the team about the case and the PR - they'll be getting in touch with you there! 🙂

**Comment by doc-rj-celltrak** [comment]
@bitce Thanks and no worries. We have bitrise.yml pointing to our fork in the meanwhile. We've enjoyed the flexibility and open source model of your product so far.

**Comment by softmarshmallow** [comment]
Any workaround before official bitrise update for flutter build?
Mine also keeps failing when flutter analyze due to warning.

**Comment by doc-rj-celltrak** [comment]
@softmarshmallow I think you can refer to the fix commit from your bitrise.yml, or you can just remove the analyze step for now.

To refer to the fix commit, i think you will need something like this:
- git::https://github.com/bitrise-steplib/bitrise-step-flutter-analyze.git@ef37011642814d20bc447b3b17b473b2399ee8de: {}

But I haven't tested it exactly like that. I'm referring to the master branch of my fork.
